import 'dart:io';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../core/constants/app_colors.dart';
import '../../core/constants/app_strings.dart';
import '../../core/constants/app_styles.dart';
import '../../core/utils/helpers.dart';
import '../../core/utils/validators.dart';
import '../../models/complaint_model.dart';
import '../../providers/auth_provider.dart';
import '../../providers/complaint_provider.dart';
import '../../widgets/custom_button.dart';
import '../../widgets/custom_text_field.dart';
import '../../widgets/image_picker_widget.dart';

class SubmitComplaintScreen extends StatefulWidget {
  const SubmitComplaintScreen({super.key});

  @override
  State<SubmitComplaintScreen> createState() => _SubmitComplaintScreenState();
}

class _SubmitComplaintScreenState extends State<SubmitComplaintScreen> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _descriptionController = TextEditingController();
  
  String _selectedCategory = 'Billing';
  List<File> _selectedImages = [];
  bool _isLoading = false;

  @override
  void dispose() {
    _titleController.dispose();
    _descriptionController.dispose();
    super.dispose();
  }

  Future<void> _handleSubmit() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);

    try {
      final auth = Provider.of<AuthProvider>(context, listen: false);
      final complaintProvider = Provider.of<ComplaintProvider>(context, listen: false);
      
      final user = auth.user;
      if (user == null) throw Exception('User not logged in');

      final complaint = ComplaintModel(
        id: '', // Generated by Firestore
        refId: Helpers.generateRefId(),
        userId: user.uid,
        userName: user.name,
        title: _titleController.text.trim(),
        description: _descriptionController.text.trim(),
        category: _selectedCategory,
        status: 'pending',
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        attachments: [], // URLs added by service
        statusHistory: [
          StatusHistoryEntry(
            status: 'pending',
            timestamp: DateTime.now(),
            note: 'Complaint submitted successfully.',
          ),
        ],
      );

      await complaintProvider.submitComplaint(complaint, images: _selectedImages);

      if (mounted) {
        setState(() => _isLoading = false);
        Helpers.showSnackBar(context, AppStrings.complaintSubmitted);
        _clearForm();
        Navigator.pop(context);
      }
    } catch (e) {
      if (mounted) {
        setState(() => _isLoading = false);
        Helpers.showSnackBar(context, 'Submission failed: ${e.toString()}', isError: true);
      }
    }
  }

  void _clearForm() {
    _titleController.clear();
    _descriptionController.clear();
    setState(() {
      _selectedCategory = 'Billing';
      _selectedImages = [];
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: AppColors.primary),
          onPressed: () => Navigator.pop(context),
        ),
        title: const Text(
          AppStrings.submitNewComplaint,
          style: TextStyle(color: AppColors.primary, fontWeight: FontWeight.bold, fontSize: 18),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(AppStrings.tellUsWhatHappened, style: AppStyles.heading2),
              const SizedBox(height: 8),
              Text(AppStrings.submitDetailSubtitle, style: AppStyles.bodySmall),
              const SizedBox(height: 32),

              // Category Selection
              const Text(AppStrings.category, style: AppStyles.labelLarge),
              const SizedBox(height: 12),
              _buildCategorySelector(),
              const SizedBox(height: 24),

              // Title
              CustomTextField(
                label: 'Complaint Title',
                hint: 'e.g. Overcharged on last bill',
                controller: _titleController,
                validator: (v) => Validators.validateRequired(v, 'Title'),
              ),
              const SizedBox(height: 24),

              // Description
              CustomTextField(
                label: AppStrings.description,
                hint: AppStrings.descriptionHint,
                controller: _descriptionController,
                maxLines: 5,
                validator: (v) => Validators.validateDescription(v),
              ),
              const SizedBox(height: 24),

              // Image Picker
              const Text(AppStrings.attachImages, style: AppStyles.labelLarge),
              const SizedBox(height: 12),
              ImagePickerWidget(
                onImagesSelected: (images) => setState(() => _selectedImages = images),
                maxImages: 3,
              ),
              const SizedBox(height: 40),

              // Submit Button
              CustomButton(
                text: AppStrings.submitComplaint,
                isLoading: _isLoading,
                onPressed: _handleSubmit,
              ),
              const SizedBox(height: 48),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildCategorySelector() {
    final categories = ['Billing', 'Technical', 'Service', 'Infrastructure'];
    return Wrap(
      spacing: 8,
      children: categories.map((cat) {
        final isSelected = _selectedCategory == cat;
        return ChoiceChip(
          label: Text(cat),
          selected: isSelected,
          onSelected: (selected) {
            if (selected) setState(() => _selectedCategory = cat);
          },
          selectedColor: AppColors.primary,
          labelStyle: TextStyle(
            color: isSelected ? Colors.white : AppColors.textPrimary,
            fontWeight: FontWeight.w600,
          ),
          showCheckmark: false,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(20),
            side: BorderSide(color: isSelected ? AppColors.primary : AppColors.divider),
          ),
        );
      }).toList(),
    );
  }
}
